#-----------------------------------------------------------------
# Server
#-----------------------------------------------------------------
server:
  port: 27101

#-----------------------------------------------------------------
# Actuator
#-----------------------------------------------------------------
endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false

#-----------------------------------------------------------------
# Spring
#-----------------------------------------------------------------
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
